#!/bin/bash

java Lab2Main recursive 1 solution_recursive_1.txt
java Lab2Main recursive 2 solution_recursive_2.txt
java Lab2Main recursive 3 solution_recursive_3.txt
java Lab2Main recursive 4 solution_recursive_4.txt
java Lab2Main recursive 5 solution_recursive_5.txt
java Lab2Main recursive 6 solution_recursive_6.txt
java Lab2Main recursive 7 solution_recursive_7.txt
java Lab2Main recursive 8 solution_recursive_8.txt
java Lab2Main recursive 9 solution_recursive_9.txt
java Lab2Main recursive 10 solution_recursive_10.txt
java Lab2Main recursive 11 solution_recursive_11.txt
java Lab2Main recursive 12 solution_recursive_12.txt
java Lab2Main recursive 13 solution_recursive_13.txt
java Lab2Main recursive 14 solution_recursive_14.txt
java Lab2Main recursive 15 solution_recursive_15.txt
java Lab2Main recursive 16 solution_recursive_16.txt
java Lab2Main recursive 17 solution_recursive_17.txt
java Lab2Main recursive 18 solution_recursive_18.txt
java Lab2Main recursive 19 solution_recursive_19.txt
java Lab2Main recursive 20 solution_recursive_20.txt
java Lab2Main recursive 21 solution_recursive_21.txt
java Lab2Main recursive 22 solution_recursive_22.txt
java Lab2Main recursive 23 solution_recursive_23.txt
java Lab2Main recursive 24 solution_recursive_24.txt
java Lab2Main recursive 25 solution_recursive_25.txt
java Lab2Main recursive 26 solution_recursive_26.txt
java Lab2Main recursive 27 solution_recursive_27.txt
java Lab2Main recursive 28 solution_recursive_28.txt
java Lab2Main recursive 29 solution_recursive_29.txt
java Lab2Main recursive 30 solution_recursive_30.txt
java Lab2Main recursive 31 solution_recursive_31.txt
java Lab2Main recursive 32 solution_recursive_32.txt
java Lab2Main recursive 33 solution_recursive_33.txt
java Lab2Main recursive 34 solution_recursive_34.txt
java Lab2Main recursive 35 solution_recursive_35.txt
java Lab2Main recursive 36 solution_recursive_36.txt
java Lab2Main recursive 37 solution_recursive_37.txt
java Lab2Main recursive 38 solution_recursive_38.txt
java Lab2Main recursive 39 solution_recursive_39.txt
java Lab2Main recursive 40 solution_recursive_40.txt
java Lab2Main recursive 41 solution_recursive_41.txt
java Lab2Main recursive 42 solution_recursive_42.txt
java Lab2Main recursive 43 solution_recursive_43.txt
java Lab2Main recursive 44 solution_recursive_44.txt
java Lab2Main recursive 45 solution_recursive_45.txt
java Lab2Main recursive 46 solution_recursive_46.txt
java Lab2Main recursive 47 solution_recursive_47.txt
java Lab2Main recursive 48 solution_recursive_48.txt
java Lab2Main recursive 49 solution_recursive_49.txt
java Lab2Main recursive 50 solution_recursive_50.txt


