#!/bin/bash

java Lab2Main recursive 1 solution_recursive_1.txt
java Lab2Main recursive 2 solution_recursive_2.txt
java Lab2Main recursive 3 solution_recursive_3.txt
java Lab2Main recursive 4 solution_recursive_4.txt
java Lab2Main recursive 5 solution_recursive_5.txt
java Lab2Main recursive 6 solution_recursive_6.txt
java Lab2Main recursive 7 solution_recursive_7.txt
java Lab2Main recursive 8 solution_recursive_8.txt
java Lab2Main recursive 9 solution_recursive_9.txt
java Lab2Main recursive 10 solution_recursive_10.txt
java Lab2Main recursive 11 solution_recursive_11.txt
java Lab2Main recursive 12 solution_recursive_12.txt
java Lab2Main recursive 13 solution_recursive_13.txt
java Lab2Main recursive 14 solution_recursive_14.txt
java Lab2Main recursive 15 solution_recursive_15.txt
java Lab2Main recursive 16 solution_recursive_16.txt
java Lab2Main recursive 17 solution_recursive_17.txt
java Lab2Main recursive 18 solution_recursive_18.txt
java Lab2Main recursive 19 solution_recursive_19.txt
java Lab2Main recursive 20 solution_recursive_20.txt
java Lab2Main recursive 21 solution_recursive_21.txt
java Lab2Main recursive 22 solution_recursive_22.txt
java Lab2Main recursive 23 solution_recursive_23.txt
java Lab2Main recursive 24 solution_recursive_24.txt
java Lab2Main recursive 25 solution_recursive_25.txt
java Lab2Main recursive 26 solution_recursive_26.txt
java Lab2Main recursive 27 solution_recursive_27.txt
java Lab2Main recursive 28 solution_recursive_28.txt
java Lab2Main recursive 29 solution_recursive_29.txt
java Lab2Main recursive 30 solution_recursive_30.txt
java Lab2Main recursive 31 solution_recursive_31.txt
java Lab2Main recursive 32 solution_recursive_32.txt
java Lab2Main recursive 33 solution_recursive_33.txt
java Lab2Main recursive 34 solution_recursive_34.txt
java Lab2Main recursive 35 solution_recursive_35.txt
java Lab2Main recursive 36 solution_recursive_36.txt
java Lab2Main recursive 37 solution_recursive_37.txt
java Lab2Main recursive 38 solution_recursive_38.txt
java Lab2Main recursive 39 solution_recursive_39.txt
java Lab2Main recursive 40 solution_recursive_40.txt
java Lab2Main recursive 41 solution_recursive_41.txt
java Lab2Main recursive 42 solution_recursive_42.txt
java Lab2Main recursive 43 solution_recursive_43.txt
java Lab2Main recursive 44 solution_recursive_44.txt
java Lab2Main recursive 45 solution_recursive_45.txt
java Lab2Main recursive 46 solution_recursive_46.txt
java Lab2Main recursive 47 solution_recursive_47.txt
java Lab2Main recursive 48 solution_recursive_48.txt
java Lab2Main recursive 49 solution_recursive_49.txt
java Lab2Main recursive 50 solution_recursive_50.txt


java Lab2Main iterative 1 solution_iterative_1.txt
java Lab2Main iterative 2 solution_iterative_2.txt
java Lab2Main iterative 3 solution_iterative_3.txt
java Lab2Main iterative 4 solution_iterative_4.txt
java Lab2Main iterative 5 solution_iterative_5.txt
java Lab2Main iterative 6 solution_iterative_6.txt
java Lab2Main iterative 7 solution_iterative_7.txt
java Lab2Main iterative 8 solution_iterative_8.txt
java Lab2Main iterative 9 solution_iterative_9.txt
java Lab2Main iterative 10 solution_iterative_10.txt
java Lab2Main iterative 11 solution_iterative_11.txt
java Lab2Main iterative 12 solution_iterative_12.txt
java Lab2Main iterative 13 solution_iterative_13.txt
java Lab2Main iterative 14 solution_iterative_14.txt
java Lab2Main iterative 15 solution_iterative_15.txt
java Lab2Main iterative 16 solution_iterative_16.txt
java Lab2Main iterative 17 solution_iterative_17.txt
java Lab2Main iterative 18 solution_iterative_18.txt
java Lab2Main iterative 19 solution_iterative_19.txt
java Lab2Main iterative 20 solution_iterative_20.txt
java Lab2Main iterative 21 solution_iterative_21.txt
java Lab2Main iterative 22 solution_iterative_22.txt
java Lab2Main iterative 23 solution_iterative_23.txt
java Lab2Main iterative 24 solution_iterative_24.txt
java Lab2Main iterative 25 solution_iterative_25.txt
java Lab2Main iterative 26 solution_iterative_26.txt
java Lab2Main iterative 27 solution_iterative_27.txt
java Lab2Main iterative 28 solution_iterative_28.txt
java Lab2Main iterative 29 solution_iterative_29.txt
java Lab2Main iterative 30 solution_iterative_30.txt
java Lab2Main iterative 31 solution_iterative_31.txt
java Lab2Main iterative 32 solution_iterative_32.txt
java Lab2Main iterative 33 solution_iterative_33.txt
java Lab2Main iterative 34 solution_iterative_34.txt
java Lab2Main iterative 35 solution_iterative_35.txt
java Lab2Main iterative 36 solution_iterative_36.txt
java Lab2Main iterative 37 solution_iterative_37.txt
java Lab2Main iterative 38 solution_iterative_38.txt
java Lab2Main iterative 39 solution_iterative_39.txt
java Lab2Main iterative 40 solution_iterative_40.txt
java Lab2Main iterative 41 solution_iterative_41.txt
java Lab2Main iterative 42 solution_iterative_42.txt
java Lab2Main iterative 43 solution_iterative_43.txt
java Lab2Main iterative 44 solution_iterative_44.txt
java Lab2Main iterative 45 solution_iterative_45.txt
java Lab2Main iterative 46 solution_iterative_46.txt
java Lab2Main iterative 47 solution_iterative_47.txt
java Lab2Main iterative 48 solution_iterative_48.txt
java Lab2Main iterative 49 solution_iterative_49.txt
java Lab2Main iterative 50 solution_iterative_50.txt
